### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by bidkar** [udo-guasave/entorno-distribuido-bidkar#5]
Crear el encabezado principal del sitio.
- [x] Logotipo
- [x] Botón hamburguesa
- [x] Menú principal

**Comment by EdbertAlan** [comment]
Es necesario que la estructura básica del proyecto este terminada para contar con los directorios donde debe colocarse el encabezado

**Comment by bidkar** [comment]
@SaikouTrolls puedes culminar la tarea de estructura básica #2 por favor, para dar continuidad a los demás pendientes.
